// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'credit_debit';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String INTRO_1_V2 = 'assets/images/intro_1_v2.png';
  static const String INTRO_2_V2 = 'assets/images/intro_2_v2.png';
  static const String INTRO_3_V2 = 'assets/images/intro_3_v2.png';
  static const String INTRO_4_V2 = 'assets/images/intro_4_v2.png';
}
