// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
import 'dart:core';

class DefaultRes {
  DefaultRes._();

  static const  PROJECT_NAME = 'credit_debit';
  static const  PROJECT_VERSION = '1.0.0+1';
  static const String = '.env';
}
